landing page draft
hubmapconsortium/ccf pull request #24
Opened 2022-07-11 17:50 UTC by bhushankhope

Created all the components on the landing page

2022-10-14 19:02 UTC, axdanbol requested changes

2022-10-14 19:02 UTC, axdanbol commented on src/app/app.module.ts
> +  providers: [TableDataService],
Remove since it is injected into root

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/bottom-toolbar/bottom-toolbar.component.scss
> +    font-family: "Inter";
Set default font-family, style, weight, and size in styles.scss

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/carousel/carousel.component.html
> +        <a mat-stroked-button class="get-button" href={{info.url}} target="_blank">Get Started</a>
Prefer `[href]="value"`

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/carousel/carousel.component.html
> +      <div *ngIf="info.url; else route">
Move ngIf to anchor element

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/carousel/carousel.component.ts
> +  constructor() { }
Remove

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/choose-version/choose-version.component.scss
> +  ::ng-deep .mat-form-field-outline {
Combine ng-deep selectors
```
::ng-deep {
  selector1 { ... }
  selector2 { ... }
}
```

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/navbar/navbar.component.html
> +<span *ngFor="let item of items">
Replace most (all?) spans with ng-container

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/navbar/navbar.component.scss
> +::ng-deep .foobar {
Whoops!

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/navbar/navbar.component.scss
> +.navigation-items > button{
Remove excessive styles

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/organ-tabs-table/organ-tabs-table.component.ts
> +export class OrganTabsTableComponent implements OnInit {
Remove entire component

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/organ-tabs/organ-tabs.component.html
> +<div class="tabs-container">
Remove top level div container. Move styles directly onto `:host`

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/organ-tabs/organ-tabs.component.scss
> +:host {
`display: block` on host

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/page-data/page-data.component.html
> +<div *ngFor="let data of data">
Replace div with ng-container

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/simple-tile/simple-tile.component.html
> +<div class="card-container">
Remove all divs and move the ngFor onto markdown

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/simple-tile/simple-tile.module.ts
> +        MarkdownModule.forRoot()
Move to app.module.ts

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/table/table.component.html
> +          <ng-template #blank></ng-template>
Remove

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/table/table.component.html
> +          <ng-container *ngIf="isNumericColumn(column.columnDef); else totalLabel">
`else: `

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/tissue-info-table/tissue-info-table.component.ts
> +  @ViewChild(MatSort) sort: MatSort;
Use setter instead of ngAfterViewInit

2022-10-14 19:02 UTC, axdanbol commented on src/app/components/toolbar/toolbar.component.html
> +  <div class="hubmap-header">{{hubmapHeader}}</div>
Inline hubmapHeader value

2022-10-14 19:02 UTC, axdanbol commented on src/app/pages/cell-population-graphs/cell-population-graphs.module.ts
> +  bootstrap: [CellPopulationGraphsComponent]
Remove

2022-10-18 17:07 UTC, merged

2022-10-18 17:08 UTC, bherr2 commented
Merged all changes into develop. From now on create PRs off of `develop`