Heidi CCF 3D library
hubmapconsortium/ccf pull request #5
Opened 2021-11-30 21:01 UTC by HeidiS25

Changed the layout- need help to center text under icons. Not ready to merge! Need to link icons and models properly, need Katy approval. First time creating a pull request on GitHub- let me know if I did anything wrong!

2021-11-30 21:14 UTC, bherr2 requested changes
The icon links and content links are broken. You'll need to either upload them or reference them from the appropriate urls.

2021-11-30 21:14 UTC, bherr2 commented on pages/ccf-3d-reference-library.html
> +                                            role="tab" aria-controls="home" aria-selected="true"><img src= "/img/icons/ico-organs-pelvis f.svg" Width=45.7px height=45.7px ><br/>Bone Marrow &<br/> Blo
Don't use starting / for links. Use '../img/XXXX'. When deployed to production it's under /ccf/ and thus all references to /img will fail.

2021-11-30 21:14 UTC, bherr2 commented on pages/ccf-3d-reference-library.html
>                                          <a class="nav-link active" id="bone-tab" data-toggle="tab" href="#bone"
A quick local check found that adding `text-align: center;` to the nav-link css definition does the trick of centering things.

2021-12-01 23:23 UTC, HeidiS25 commented
Hi Bruce- I sent a Slack convo about this- not sure icons are still pulling, but hopefully the rest is ok. Let me know. Thanks!

2021-12-02 18:59 UTC, HeidiS25 commented
Bruce- I want to preview these latest changes to Katy- is there a way she can see it without being live to the public?

2021-12-17 21:18 UTC, merged